name: Publish to NPM

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Node installation
          uses: actions/setup-node@v3
          with:
            node-version: 20
            registry-url: 'https://registry.npmjs.org'
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        - name: Dependencies installation
          uses: borales/actions-yarn@v4
          with:
            cmd: install

        - name: Build
          uses: borales/actions-yarn@v4
          with:
            cmd: build

        - name: Configure npm
          run: |
            echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
            cat .npmrc
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        - name: Publish
          run: npm publish --provenance --access public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
